CREATE TABLE [dbo].[tmp_tirages] (
    [Id_Tirage]         NVARCHAR (256) NULL,
    [Code_Lot]          NVARCHAR (256) NULL,
    [Code_Article]      NVARCHAR (256) NULL,
    [Num_Tirage]        NVARCHAR (256) NULL,
    [Num_Suite]         NVARCHAR (256) NULL,
    [Prix]              NVARCHAR (256) NULL,
    [Coffret]           NVARCHAR (256) NULL,
    [Filiere_Princ]     NVARCHAR (256) NULL,
    [Interv_tech]       NVARCHAR (256) NULL,
    [Disquette]         NVARCHAR (256) NULL,
    [Couverture]        NVARCHAR (256) NULL,
    [Encart]            NVARCHAR (256) NULL,
    [Hors__Texte]       NVARCHAR (256) NULL,
    [Comment_HT]        NVARCHAR (256) NULL,
    [Ill_Interieur]     NVARCHAR (256) NULL,
    [Comment_Ilint]     NVARCHAR (256) NULL,
    [Jaquette]          NVARCHAR (256) NULL,
    [Rhodoid]           NVARCHAR (256) NULL,
    [Bande]             NVARCHAR (256) NULL,
    [Standard_FP]       NVARCHAR (256) NULL,
    [Heures_FP]         NVARCHAR (256) NULL,
    [Standard_ADM]      NVARCHAR (256) NULL,
    [Standard_ADM_GR]   NVARCHAR (256) NULL,
    [Mode_Compo]        NVARCHAR (256) NULL,
    [Compositeur]       NVARCHAR (256) NULL,
    [Imprimeur_Txt]     NVARCHAR (256) NULL,
    [PAO_Atelier]       NVARCHAR (256) NULL,
    [Poids]             NVARCHAR (256) NULL,
    [Dos_Largeur]       NVARCHAR (256) NULL,
    [Date_Liv_Ball]     NVARCHAR (256) NULL,
    [Qte_Liv_Ball]      NVARCHAR (256) NULL,
    [Qte_Tirage]        NVARCHAR (256) NULL,
    [Niveau_Excel]      NVARCHAR (256) NULL,
    [Num_Version]       NVARCHAR (256) NULL,
    [Date_Maj]          NVARCHAR (256) NULL,
    [User]              NVARCHAR (256) NULL,
    [Brochage]          NVARCHAR (256) NULL,
    [Papier]            NVARCHAR (256) NULL,
    [Standard_PAO]      NVARCHAR (256) NULL,
    [Avis_A_Editer]     NVARCHAR (256) NULL,
    [Lecture_Optique]   NVARCHAR (256) NULL,
    [Saisie_Collab]     NVARCHAR (256) NULL,
    [Nom_Collab]        NVARCHAR (256) NULL,
    [Heures_Collab]     NVARCHAR (256) NULL,
    [Saisie_Ext]        NVARCHAR (256) NULL,
    [Nom_Ext]           NVARCHAR (256) NULL,
    [Prix_Ext]          NVARCHAR (256) NULL,
    [Reprise_Compo]     NVARCHAR (256) NULL,
    [Coef_Imp_Fac]      NVARCHAR (256) NULL,
    [Coef_Accessoire]   NVARCHAR (256) NULL,
    [Coef_Papier]       NVARCHAR (256) NULL,
    [Diffu_Trad]        NVARCHAR (256) NULL,
    [Maquette_cout]     NVARCHAR (256) NULL,
    [Diffu_Correc]      NVARCHAR (256) NULL,
    [Nb_Correc]         NVARCHAR (256) NULL,
    [Labo_Cout]         NVARCHAR (256) NULL,
    [Photocopies]       NVARCHAR (256) NULL,
    [Type_Brochage]     NVARCHAR (256) NULL,
    [Prepa_Collab]      NVARCHAR (256) NULL,
    [Prepa_Ext]         NVARCHAR (256) NULL,
    [Prepa_Nom]         NVARCHAR (256) NULL,
    [Prepa_Entrepris]   NVARCHAR (256) NULL,
    [Prepa_Heures]      NVARCHAR (256) NULL,
    [Prepa_Cout]        NVARCHAR (256) NULL,
    [Couv_a_Rabats]     NVARCHAR (256) NULL,
    [Type_Real]         NVARCHAR (256) NULL,
    [Fil_PAO_Atel]      NVARCHAR (256) NULL,
    [Fil_PAO_Graph]     NVARCHAR (256) NULL,
    [Fil_Icono]         NVARCHAR (256) NULL,
    [Fil_Technique]     NVARCHAR (256) NULL,
    [Fil_LG]            NVARCHAR (256) NULL,
    [Fil_Hors_Stand]    NVARCHAR (256) NULL,
    [Fil_Artistique]    NVARCHAR (256) NULL,
    [flags]             NVARCHAR (256) NULL,
    [Preparateur]       NVARCHAR (256) NULL,
    [flags_FT]          NVARCHAR (256) NULL,
    [Tire_a_Part]       NVARCHAR (256) NULL,
    [No_Devis]          NVARCHAR (256) NULL,
    [Qte_Mep]           NVARCHAR (256) NULL,
    [Standard_Lect]     NVARCHAR (256) NULL,
    [Pao_Heures]        NVARCHAR (256) NULL,
    [Qte_Liv_SP]        NVARCHAR (256) NULL,
    [Date_Liv_SP]       NVARCHAR (256) NULL,
    [phases]            NVARCHAR (256) NULL,
    [filme a unite]     NVARCHAR (256) NULL,
    [no_avis_imp]       NVARCHAR (256) NULL,
    [date creation]     NVARCHAR (256) NULL,
    [code_processus]    NVARCHAR (256) NULL,
    [date_modification] NVARCHAR (256) NULL,
    [codeTirageEdition] NVARCHAR (256) NULL,
    [Collection]        NVARCHAR (56)  NULL
);






GO
CREATE CLUSTERED INDEX [index_Id_Tirage]
    ON [dbo].[tmp_tirages]([Id_Tirage] ASC);

